---------------
-- TABELAS
---------------

CREATE TABLE DEPARTAMENTO (
       COD_DEPART int(4),
       NOME varchar(30) NOT NULL,
       DATA_INICIAL Date
);

CREATE TABLE FUNCIONARIO (
       COD_FUNC int(4),
       NOME varchar(100) NOT NULL,
       CPF varchar(15),
       SALARIO numeric(8,2),
       ENDERECO varchar(252),
       SEXO char(1),
       COD_SUPER int(4),
       COD_DEPART int(4)
);

CREATE TABLE DEPENDENTE (
       COD_FUNC int(4),
       SEQ int(4),
       NOME varchar(100) NOT NULL,
       PARENTESCO varchar(30) NOT NULL,
       DATA_NASC Date
);

CREATE TABLE PROJETO (
       COD_PROJ int(4),
       COD_DEPART int(4),
       TITULO varchar(150) NOT NULL,
       DESCRICAO varchar(252),
       DATA_CAD Date DEFAULT sysdate
);

CREATE TABLE PARTICIPA (
       COD_FUNC int(4),
       COD_PROJ int(4),
       HORAS varchar(50)
);

CREATE TABLE LOCALIZACAO (
       COD_DEPART int(4),
       LOCALIZA varchar(252)
);

---------------
-- PRIMARY KEY's
---------------

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPT_COD_DEPART
      PRIMARY KEY(COD_DEPART);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNC_COD_FUNC
      PRIMARY KEY(COD_FUNC);

ALTER TABLE PROJETO ADD CONSTRAINT PK_PROJETO_COD_FUNC
            PRIMARY KEY(COD_PROJ);
 
ALTER TABLE PARTICIPA ADD CONSTRAINT PK_COD_FUNC_COD_PROJ
      PRIMARY KEY(COD_FUNC,COD_PROJ);
      
ALTER TABLE LOCALIZACAO ADD CONSTRAINT PK_LOCALIZ_COD_DEPART_LOCAL
      PRIMARY KEY(COD_DEPART,LOCALIZA);
      
ALTER TABLE DEPENDENTE ADD CONSTRAINT PK_DEPEND_COD_FUNC_SEQ
      PRIMARY KEY(COD_FUNC,SEQ);

---------------
-- FOREIGN KEY's
---------------

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCION_COD_SUPER
      FOREIGN KEY(COD_SUPER) REFERENCES FUNCIONARIO (COD_FUNC);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCION_COD_DEPART
      FOREIGN KEY(COD_DEPART) REFERENCES DEPARTAMENTO (COD_DEPART);

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPEND_COD_FUNC
      FOREIGN KEY(COD_FUNC) REFERENCES FUNCIONARIO (COD_FUNC);
       
ALTER TABLE PROJETO ADD CONSTRAINT FK_PROJETO_COD_DEPART
      FOREIGN KEY(COD_DEPART) REFERENCES DEPARTAMENTO (COD_DEPART);
                  
ALTER TABLE PARTICIPA ADD CONSTRAINT FK_PARTICIPA_COD_FUNC
      FOREIGN KEY(COD_FUNC) REFERENCES FUNCIONARIO (COD_FUNC);
      
ALTER TABLE PARTICIPA ADD CONSTRAINT FK_PARTICIPA_COD_PROJ
      FOREIGN KEY(COD_PROJ) REFERENCES PROJETO (COD_PROJ);

ALTER TABLE LOCALIZACAO ADD CONSTRAINT FK_LOCALIZ_COD_DEPART
      FOREIGN KEY(COD_DEPART) REFERENCES DEPARTAMENTO (COD_DEPART);
      
---------------
-- UNIQUE KEY's
---------------

ALTER TABLE FUNCIONARIO ADD CONSTRAINT UK_FUNCION_CPF UNIQUE(CPF);

---------------
-- CHECK KEY's
---------------


ALTER TABLE FUNCIONARIO ADD CONSTRAINT CK_FUNCION_SEXO CHECK(SEXO IN ('M','F'));

ALTER TABLE DEPENDENTE ADD CONSTRAINT CK_DEPEND_PARENTESCO
      CHECK(PARENTESCO IN ('PAI','MAE','IRMAOS','FILHO'));
